flowchart TD
    A[Пользователь] --> B[Приветствие]
    B --> C{Меню}

    C --> C1[Консультация со специалистом]
    C --> C2[Консультация с ИИ]
    C --> C3[Условия обращения]
    C --> C4[Вопрос по психологии]

    C3 --> D1[Показ условий и политики]

    C2 --> D2[Подключение ИИ ассистента]
    D2 --> D3[Диалог с ИИ]
    D3 --> D4[Очистка контекста]
    D3 --> D5[Возврат в меню]
    D5 --> C

    C1 --> E[Сбор данных пользователя]
    E --> E1[Тема]
    E --> E2[Пол]
    E --> E3[Возраст]
    E --> E4[Критичность]
    E --> E5[Сообщение]

    E5 --> F[Создание заявки]

    F --> G[Карточка заявки]
    G --> G1[ID и статус Новое]

    G --> H[Очередь заявок]

    H --> H1[Открыть заявку]
    H --> H2[Взять в работу]
    H --> H3[Изменить статус]
    H --> H4[Изменить критичность]
    H --> H5[Начать чат]

    H2 --> I[Статус В работе]

    H3 --> J{Статус}
    J --> J1[Новое]
    J --> J2[В работе]
    J --> J3[Ожидание ответа]
    J --> J4[Закрыто]

    H5 --> L[Анонимный чат]
    L --> L1[История сохраняется]
